# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: maxwest@uw.edu
author_name: Maxine West
custom_install: false
package_name: koffi
project_license: BSD
project_name: koffi
project_organization: lincc-frameworks
