# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: maxwest@uw.edu
author_name: Maxine West
create_example_module: false
custom_install: true
enforce_style:
- black
- isort
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: false
mypy_type_checking: none
package_name: koffi
project_license: BSD
project_name: koffi
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
